/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.ArrayList;
import java.util.Scanner;

public class miguelmoran_examen1p2 extends javax.swing.JFrame {

    ArrayList<PC> computadoras = new ArrayList<>();
    Scanner sc = new Scanner(System.in);

    public miguelmoran_examen1p2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoPC_Label = new javax.swing.JLabel();
        TipoPC_ComboBox = new javax.swing.JComboBox<>();
        IP_Label = new javax.swing.JLabel();
        IP_TextField = new javax.swing.JTextField();
        Mascara_Label = new javax.swing.JLabel();
        Mascara_TextField = new javax.swing.JTextField();
        Nombre_Label = new javax.swing.JLabel();
        Nombre_TextField = new javax.swing.JTextField();
        PCdeEscritorio_Label = new javax.swing.JLabel();
        RAM_Label = new javax.swing.JLabel();
        Memoria_Label = new javax.swing.JLabel();
        Memoria_TextField = new javax.swing.JTextField();
        TipodeMemoria_Label = new javax.swing.JLabel();
        Grafica_Label = new javax.swing.JLabel();
        TarjetaGrafica_ComboBox = new javax.swing.JComboBox<>();
        Laptop_Label = new javax.swing.JLabel();
        Marca_Label = new javax.swing.JLabel();
        Marca_TextField = new javax.swing.JTextField();
        Definicion_Label = new javax.swing.JLabel();
        Definicion_TextField = new javax.swing.JTextField();
        RGB_Label = new javax.swing.JLabel();
        RGB_ComboBox = new javax.swing.JComboBox<>();
        Crear_Button = new javax.swing.JButton();
        TipoMemoria_ComboBox = new javax.swing.JComboBox<>();
        Ingresar_Label = new javax.swing.JLabel();
        Ingresar_ComboBox = new javax.swing.JComboBox<>();
        RAM_TextField = new javax.swing.JTextField();
        Ingresar_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TipoPC_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TipoPC_Label.setText("Tipo de PC:");

        TipoPC_ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TipoPC_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de Escritorio", "Laptop" }));

        IP_Label.setText("Direccion IP:");

        Mascara_Label.setText("Marcara de red:");

        Nombre_Label.setText("Hostname:");

        PCdeEscritorio_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PCdeEscritorio_Label.setText("PC de Escritorio");

        RAM_Label.setText("Memoria RAM:");

        Memoria_Label.setText("Capacidad de Memoria:");

        TipodeMemoria_Label.setText("Tipo de Memoria:");

        Grafica_Label.setText("Tarjeta Grafica:");

        TarjetaGrafica_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        Laptop_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Laptop_Label.setText("Laptop");

        Marca_Label.setText("Marca:");

        Definicion_Label.setText("Definicion de Pantalla:");

        RGB_Label.setText("Teclado RGB:");

        RGB_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        Crear_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Crear_Button.setText("Crear");
        Crear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_ButtonActionPerformed(evt);
            }
        });

        TipoMemoria_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HDD", "SSD" }));

        Ingresar_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ingresar_Label.setText("Ingresar con:");

        Ingresar_ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Ingresar_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ingresar_Button.setText("Ingresar");
        Ingresar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ingresar_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ingresar_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TipoPC_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TipoPC_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(Crear_Button))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(Ingresar_Button)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mascara_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mascara_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IP_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IP_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Grafica_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TarjetaGrafica_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PCdeEscritorio_Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RAM_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RAM_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Memoria_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Memoria_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TipodeMemoria_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TipoMemoria_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Laptop_Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Marca_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Marca_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Definicion_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Definicion_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RGB_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RGB_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoPC_Label)
                    .addComponent(TipoPC_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IP_Label)
                    .addComponent(IP_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mascara_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mascara_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_Label)
                    .addComponent(Nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crear_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PCdeEscritorio_Label)
                    .addComponent(Laptop_Label))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RAM_Label)
                            .addComponent(Marca_Label)
                            .addComponent(Marca_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RAM_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ingresar_Label)
                            .addComponent(Ingresar_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Memoria_Label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Memoria_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Definicion_Label)
                        .addComponent(Definicion_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipodeMemoria_Label)
                    .addComponent(RGB_Label)
                    .addComponent(RGB_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoMemoria_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ingresar_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grafica_Label)
                    .addComponent(TarjetaGrafica_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_ButtonActionPerformed
        if (PC.IPValido(IP_TextField.getText()) && PC.IPValido(Mascara_TextField.getText())) {
            if (TipoPC_ComboBox.getSelectedIndex() == 0) {
                if (TarjetaGrafica_ComboBox.getSelectedIndex() == 0) {
                    computadoras.add(new de_Escritorio(Integer.parseInt(RAM_TextField.getText()), Integer.parseInt(Memoria_TextField.getText()), TipoMemoria_ComboBox.getSelectedItem().toString(), true, IP_TextField.getText(), Mascara_TextField.getText(), Nombre_TextField.getText()));
                } else {
                    computadoras.add(new de_Escritorio(Integer.parseInt(RAM_TextField.getText()), Integer.parseInt(Memoria_TextField.getText()), TipoMemoria_ComboBox.getSelectedItem().toString(), false, IP_TextField.getText(), Mascara_TextField.getText(), Nombre_TextField.getText()));
                }
            } else {
                if (RGB_ComboBox.getSelectedIndex() == 0) {
                    computadoras.add(new Laptop(Marca_TextField.getText(), Definicion_TextField.getText(), true, IP_TextField.getText(), Mascara_TextField.getText(), Nombre_TextField.getText()));
                } else {
                    computadoras.add(new Laptop(Marca_TextField.getText(), Definicion_TextField.getText(), true, IP_TextField.getText(), Mascara_TextField.getText(), Nombre_TextField.getText()));
                }
            }
            Ingresar_ComboBox.addItem(Nombre_TextField.getText());
            RAM_TextField.setText("");
            Memoria_TextField.setText("");
            IP_TextField.setText("");
            Mascara_TextField.setText("");
            Nombre_TextField.setText("");
            Marca_TextField.setText("");
            Definicion_TextField.setText("");
        }
    }//GEN-LAST:event_Crear_ButtonActionPerformed

    private void Ingresar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_ButtonActionPerformed
        if (!Ingresar_ComboBox.getSelectedItem().equals("")) {
            this.setVisible(false);
            boolean seguir = true;
            while (seguir) {
                System.out.print(Ingresar_ComboBox.getSelectedItem() + "#");
                String comando = sc.next();
                if (comando.equalsIgnoreCase("exit")) {
                    this.setVisible(true);
                    seguir = false;
                } else if (comando.equalsIgnoreCase("show")) {
                    System.out.println("IP: " + computadoras.get(Ingresar_ComboBox.getSelectedIndex()).getIp());
                    System.out.println("Mascara: " + computadoras.get(Ingresar_ComboBox.getSelectedIndex()).getMascara());
                } else {
                    System.out.println("comando invalido");
                }
            }
        }
    }//GEN-LAST:event_Ingresar_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miguelmoran_examen1p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miguelmoran_examen1p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miguelmoran_examen1p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miguelmoran_examen1p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miguelmoran_examen1p2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear_Button;
    private javax.swing.JLabel Definicion_Label;
    private javax.swing.JTextField Definicion_TextField;
    private javax.swing.JLabel Grafica_Label;
    private javax.swing.JLabel IP_Label;
    private javax.swing.JTextField IP_TextField;
    private javax.swing.JButton Ingresar_Button;
    private javax.swing.JComboBox<String> Ingresar_ComboBox;
    private javax.swing.JLabel Ingresar_Label;
    private javax.swing.JLabel Laptop_Label;
    private javax.swing.JLabel Marca_Label;
    private javax.swing.JTextField Marca_TextField;
    private javax.swing.JLabel Mascara_Label;
    private javax.swing.JTextField Mascara_TextField;
    private javax.swing.JLabel Memoria_Label;
    private javax.swing.JTextField Memoria_TextField;
    private javax.swing.JLabel Nombre_Label;
    private javax.swing.JTextField Nombre_TextField;
    private javax.swing.JLabel PCdeEscritorio_Label;
    private javax.swing.JLabel RAM_Label;
    private javax.swing.JTextField RAM_TextField;
    private javax.swing.JComboBox<String> RGB_ComboBox;
    private javax.swing.JLabel RGB_Label;
    private javax.swing.JComboBox<String> TarjetaGrafica_ComboBox;
    private javax.swing.JComboBox<String> TipoMemoria_ComboBox;
    private javax.swing.JComboBox<String> TipoPC_ComboBox;
    private javax.swing.JLabel TipoPC_Label;
    private javax.swing.JLabel TipodeMemoria_Label;
    // End of variables declaration//GEN-END:variables
}
